apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: kafka-cluster-app
 namespace: argocd
spec:
 project: default
 source:
   repoURL: 'https://github.com/D-Thatcher/eks_kafka_starter'
   targetRevision: HEAD
   path: 'k8s/kafka-cluster'
 destination:
   server: 'https://kubernetes.default.svc'
   namespace: example-cluster
 syncPolicy:
   automated:
     prune: true
     selfHeal: true
   syncOptions:
   - CreateNamespace=true