apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: kafka-operator-argo
 namespace: argocd
spec:
 project: default
 source:
   chart: strimzi-kafka-operator
   repoURL: quay.io/strimzi-helm
   targetRevision: 0.45.0
 destination:
   server: 'https://kubernetes.default.svc'
   namespace: kafka
 syncPolicy:
   automated:
     prune: true
     selfHeal: true
   syncOptions:
   - CreateNamespace=true